---
resources:
- name: Pipeline_resources
  type: git
  source:
    branch: master
    uri: https://github.com/thibfilipe/Terra-Concourse-plan

- name: Terradev-test
  type: git
  source:
    uri: https://github.com/thibfilipe/pushtest


jobs:
- name: Terra-Init-Plan
  plan:
  - get: Terradev-test
    trigger: true
  - get: Pipeline_resources
    trigger: true
  - task: task_terra-init-plan
    file: Pipeline_resources/terra-concourse_project/task_terra-init-plan.yml

    
- name: Terra-Apply
  plan:
  - get: Terradev-test
    passed:
      - Terra-Init-Plan
  - get: Pipeline_resources
    passed:
      - Terra-Init-Plan
    trigger: false
  - task: task_terra-apply
    file: Pipeline_resources/terra-concourse_project/task_terra-apply.yml
    
- name: Merge
  plan:
  - get: Terradev-test
    passed:
      - Terra-Apply
    trigger: false
  - get: Pipeline_resources
    passed:
      - Terra-Apply
    trigger: false
  - task: task_commit
    file: Pipeline_resources/terra-concourse_project/task_commit.yml